# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import songservice_pb2 as songservice__pb2


class SongServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/songservice.SongService/Add',
        request_serializer=songservice__pb2.AddSongRequest.SerializeToString,
        response_deserializer=songservice__pb2.Empty.FromString,
        )
    self.Update = channel.unary_unary(
        '/songservice.SongService/Update',
        request_serializer=songservice__pb2.UpdateSongRequest.SerializeToString,
        response_deserializer=songservice__pb2.Empty.FromString,
        )
    self.Get = channel.unary_unary(
        '/songservice.SongService/Get',
        request_serializer=songservice__pb2.GetSongRequest.SerializeToString,
        response_deserializer=songservice__pb2.GetSongResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/songservice.SongService/Delete',
        request_serializer=songservice__pb2.DeleteSongRequest.SerializeToString,
        response_deserializer=songservice__pb2.Empty.FromString,
        )


class SongServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SongServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=songservice__pb2.AddSongRequest.FromString,
          response_serializer=songservice__pb2.Empty.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=songservice__pb2.UpdateSongRequest.FromString,
          response_serializer=songservice__pb2.Empty.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=songservice__pb2.GetSongRequest.FromString,
          response_serializer=songservice__pb2.GetSongResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=songservice__pb2.DeleteSongRequest.FromString,
          response_serializer=songservice__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'songservice.SongService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
