# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: songservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='songservice.proto',
  package='songservice',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11songservice.proto\x12\x0bsongservice\"4\n\x0e\x41\x64\x64SongRequest\x12\"\n\x07newSong\x18\x01 \x01(\x0b\x32\x11.songservice.Song\"K\n\x11UpdateSongRequest\x12\x0e\n\x06songID\x18\x01 \x01(\t\x12&\n\x0bupdatedSong\x18\x02 \x01(\x0b\x32\x11.songservice.Song\"?\n\x0eGetSongRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61rtists\x18\x02 \x03(\t\x12\x0e\n\x06songID\x18\x03 \x01(\t\"\x8f\x01\n\x0fGetSongResponse\x12:\n\x06result\x18\x01 \x03(\x0b\x32*.songservice.GetSongResponse.GetSongResult\x1a@\n\rGetSongResult\x12\x1f\n\x04song\x18\x01 \x01(\x0b\x32\x11.songservice.Song\x12\x0e\n\x06songID\x18\x02 \x01(\t\"#\n\x11\x44\x65leteSongRequest\x12\x0e\n\x06SongID\x18\x01 \x01(\t\"4\n\x04Song\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61rtists\x18\x02 \x03(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\x0c\"\x07\n\x05\x45mpty2\x8b\x02\n\x0bSongService\x12\x38\n\x03\x41\x64\x64\x12\x1b.songservice.AddSongRequest\x1a\x12.songservice.Empty\"\x00\x12>\n\x06Update\x12\x1e.songservice.UpdateSongRequest\x1a\x12.songservice.Empty\"\x00\x12\x42\n\x03Get\x12\x1b.songservice.GetSongRequest\x1a\x1c.songservice.GetSongResponse\"\x00\x12>\n\x06\x44\x65lete\x12\x1e.songservice.DeleteSongRequest\x1a\x12.songservice.Empty\"\x00\x62\x06proto3')
)




_ADDSONGREQUEST = _descriptor.Descriptor(
  name='AddSongRequest',
  full_name='songservice.AddSongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newSong', full_name='songservice.AddSongRequest.newSong', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=86,
)


_UPDATESONGREQUEST = _descriptor.Descriptor(
  name='UpdateSongRequest',
  full_name='songservice.UpdateSongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='songID', full_name='songservice.UpdateSongRequest.songID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updatedSong', full_name='songservice.UpdateSongRequest.updatedSong', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=163,
)


_GETSONGREQUEST = _descriptor.Descriptor(
  name='GetSongRequest',
  full_name='songservice.GetSongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='songservice.GetSongRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artists', full_name='songservice.GetSongRequest.artists', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='songID', full_name='songservice.GetSongRequest.songID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=228,
)


_GETSONGRESPONSE_GETSONGRESULT = _descriptor.Descriptor(
  name='GetSongResult',
  full_name='songservice.GetSongResponse.GetSongResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='song', full_name='songservice.GetSongResponse.GetSongResult.song', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='songID', full_name='songservice.GetSongResponse.GetSongResult.songID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=374,
)

_GETSONGRESPONSE = _descriptor.Descriptor(
  name='GetSongResponse',
  full_name='songservice.GetSongResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='songservice.GetSongResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETSONGRESPONSE_GETSONGRESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=374,
)


_DELETESONGREQUEST = _descriptor.Descriptor(
  name='DeleteSongRequest',
  full_name='songservice.DeleteSongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SongID', full_name='songservice.DeleteSongRequest.SongID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=411,
)


_SONG = _descriptor.Descriptor(
  name='Song',
  full_name='songservice.Song',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='songservice.Song.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='artists', full_name='songservice.Song.artists', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='songservice.Song.audio', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=465,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='songservice.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=474,
)

_ADDSONGREQUEST.fields_by_name['newSong'].message_type = _SONG
_UPDATESONGREQUEST.fields_by_name['updatedSong'].message_type = _SONG
_GETSONGRESPONSE_GETSONGRESULT.fields_by_name['song'].message_type = _SONG
_GETSONGRESPONSE_GETSONGRESULT.containing_type = _GETSONGRESPONSE
_GETSONGRESPONSE.fields_by_name['result'].message_type = _GETSONGRESPONSE_GETSONGRESULT
DESCRIPTOR.message_types_by_name['AddSongRequest'] = _ADDSONGREQUEST
DESCRIPTOR.message_types_by_name['UpdateSongRequest'] = _UPDATESONGREQUEST
DESCRIPTOR.message_types_by_name['GetSongRequest'] = _GETSONGREQUEST
DESCRIPTOR.message_types_by_name['GetSongResponse'] = _GETSONGRESPONSE
DESCRIPTOR.message_types_by_name['DeleteSongRequest'] = _DELETESONGREQUEST
DESCRIPTOR.message_types_by_name['Song'] = _SONG
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddSongRequest = _reflection.GeneratedProtocolMessageType('AddSongRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDSONGREQUEST,
  __module__ = 'songservice_pb2'
  # @@protoc_insertion_point(class_scope:songservice.AddSongRequest)
  ))
_sym_db.RegisterMessage(AddSongRequest)

UpdateSongRequest = _reflection.GeneratedProtocolMessageType('UpdateSongRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATESONGREQUEST,
  __module__ = 'songservice_pb2'
  # @@protoc_insertion_point(class_scope:songservice.UpdateSongRequest)
  ))
_sym_db.RegisterMessage(UpdateSongRequest)

GetSongRequest = _reflection.GeneratedProtocolMessageType('GetSongRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSONGREQUEST,
  __module__ = 'songservice_pb2'
  # @@protoc_insertion_point(class_scope:songservice.GetSongRequest)
  ))
_sym_db.RegisterMessage(GetSongRequest)

GetSongResponse = _reflection.GeneratedProtocolMessageType('GetSongResponse', (_message.Message,), dict(

  GetSongResult = _reflection.GeneratedProtocolMessageType('GetSongResult', (_message.Message,), dict(
    DESCRIPTOR = _GETSONGRESPONSE_GETSONGRESULT,
    __module__ = 'songservice_pb2'
    # @@protoc_insertion_point(class_scope:songservice.GetSongResponse.GetSongResult)
    ))
  ,
  DESCRIPTOR = _GETSONGRESPONSE,
  __module__ = 'songservice_pb2'
  # @@protoc_insertion_point(class_scope:songservice.GetSongResponse)
  ))
_sym_db.RegisterMessage(GetSongResponse)
_sym_db.RegisterMessage(GetSongResponse.GetSongResult)

DeleteSongRequest = _reflection.GeneratedProtocolMessageType('DeleteSongRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETESONGREQUEST,
  __module__ = 'songservice_pb2'
  # @@protoc_insertion_point(class_scope:songservice.DeleteSongRequest)
  ))
_sym_db.RegisterMessage(DeleteSongRequest)

Song = _reflection.GeneratedProtocolMessageType('Song', (_message.Message,), dict(
  DESCRIPTOR = _SONG,
  __module__ = 'songservice_pb2'
  # @@protoc_insertion_point(class_scope:songservice.Song)
  ))
_sym_db.RegisterMessage(Song)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'songservice_pb2'
  # @@protoc_insertion_point(class_scope:songservice.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_SONGSERVICE = _descriptor.ServiceDescriptor(
  name='SongService',
  full_name='songservice.SongService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=477,
  serialized_end=744,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='songservice.SongService.Add',
    index=0,
    containing_service=None,
    input_type=_ADDSONGREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='songservice.SongService.Update',
    index=1,
    containing_service=None,
    input_type=_UPDATESONGREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='songservice.SongService.Get',
    index=2,
    containing_service=None,
    input_type=_GETSONGREQUEST,
    output_type=_GETSONGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='songservice.SongService.Delete',
    index=3,
    containing_service=None,
    input_type=_DELETESONGREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SONGSERVICE)

DESCRIPTOR.services_by_name['SongService'] = _SONGSERVICE

# @@protoc_insertion_point(module_scope)
