// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/songservice.proto

package songservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddSongRequest struct {
	NewSong              *Song    `protobuf:"bytes,1,opt,name=newSong,proto3" json:"newSong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSongRequest) Reset()         { *m = AddSongRequest{} }
func (m *AddSongRequest) String() string { return proto.CompactTextString(m) }
func (*AddSongRequest) ProtoMessage()    {}
func (*AddSongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a965d53506cc0f82, []int{0}
}

func (m *AddSongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSongRequest.Unmarshal(m, b)
}
func (m *AddSongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSongRequest.Marshal(b, m, deterministic)
}
func (m *AddSongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSongRequest.Merge(m, src)
}
func (m *AddSongRequest) XXX_Size() int {
	return xxx_messageInfo_AddSongRequest.Size(m)
}
func (m *AddSongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSongRequest proto.InternalMessageInfo

func (m *AddSongRequest) GetNewSong() *Song {
	if m != nil {
		return m.NewSong
	}
	return nil
}

type UpdateSongRequest struct {
	SongID               string   `protobuf:"bytes,1,opt,name=songID,proto3" json:"songID,omitempty"`
	UpdatedSong          *Song    `protobuf:"bytes,2,opt,name=updatedSong,proto3" json:"updatedSong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSongRequest) Reset()         { *m = UpdateSongRequest{} }
func (m *UpdateSongRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSongRequest) ProtoMessage()    {}
func (*UpdateSongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a965d53506cc0f82, []int{1}
}

func (m *UpdateSongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSongRequest.Unmarshal(m, b)
}
func (m *UpdateSongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSongRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSongRequest.Merge(m, src)
}
func (m *UpdateSongRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSongRequest.Size(m)
}
func (m *UpdateSongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSongRequest proto.InternalMessageInfo

func (m *UpdateSongRequest) GetSongID() string {
	if m != nil {
		return m.SongID
	}
	return ""
}

func (m *UpdateSongRequest) GetUpdatedSong() *Song {
	if m != nil {
		return m.UpdatedSong
	}
	return nil
}

type GetSongRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artists              []string `protobuf:"bytes,2,rep,name=artists,proto3" json:"artists,omitempty"`
	SongID               string   `protobuf:"bytes,3,opt,name=songID,proto3" json:"songID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSongRequest) Reset()         { *m = GetSongRequest{} }
func (m *GetSongRequest) String() string { return proto.CompactTextString(m) }
func (*GetSongRequest) ProtoMessage()    {}
func (*GetSongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a965d53506cc0f82, []int{2}
}

func (m *GetSongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSongRequest.Unmarshal(m, b)
}
func (m *GetSongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSongRequest.Marshal(b, m, deterministic)
}
func (m *GetSongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSongRequest.Merge(m, src)
}
func (m *GetSongRequest) XXX_Size() int {
	return xxx_messageInfo_GetSongRequest.Size(m)
}
func (m *GetSongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSongRequest proto.InternalMessageInfo

func (m *GetSongRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetSongRequest) GetArtists() []string {
	if m != nil {
		return m.Artists
	}
	return nil
}

func (m *GetSongRequest) GetSongID() string {
	if m != nil {
		return m.SongID
	}
	return ""
}

type GetSongResponse struct {
	Result               []*GetSongResponse_GetSongResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetSongResponse) Reset()         { *m = GetSongResponse{} }
func (m *GetSongResponse) String() string { return proto.CompactTextString(m) }
func (*GetSongResponse) ProtoMessage()    {}
func (*GetSongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a965d53506cc0f82, []int{3}
}

func (m *GetSongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSongResponse.Unmarshal(m, b)
}
func (m *GetSongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSongResponse.Marshal(b, m, deterministic)
}
func (m *GetSongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSongResponse.Merge(m, src)
}
func (m *GetSongResponse) XXX_Size() int {
	return xxx_messageInfo_GetSongResponse.Size(m)
}
func (m *GetSongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSongResponse proto.InternalMessageInfo

func (m *GetSongResponse) GetResult() []*GetSongResponse_GetSongResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetSongResponse_GetSongResult struct {
	Song                 *Song    `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	SongID               string   `protobuf:"bytes,2,opt,name=songID,proto3" json:"songID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSongResponse_GetSongResult) Reset()         { *m = GetSongResponse_GetSongResult{} }
func (m *GetSongResponse_GetSongResult) String() string { return proto.CompactTextString(m) }
func (*GetSongResponse_GetSongResult) ProtoMessage()    {}
func (*GetSongResponse_GetSongResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a965d53506cc0f82, []int{3, 0}
}

func (m *GetSongResponse_GetSongResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSongResponse_GetSongResult.Unmarshal(m, b)
}
func (m *GetSongResponse_GetSongResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSongResponse_GetSongResult.Marshal(b, m, deterministic)
}
func (m *GetSongResponse_GetSongResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSongResponse_GetSongResult.Merge(m, src)
}
func (m *GetSongResponse_GetSongResult) XXX_Size() int {
	return xxx_messageInfo_GetSongResponse_GetSongResult.Size(m)
}
func (m *GetSongResponse_GetSongResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSongResponse_GetSongResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetSongResponse_GetSongResult proto.InternalMessageInfo

func (m *GetSongResponse_GetSongResult) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

func (m *GetSongResponse_GetSongResult) GetSongID() string {
	if m != nil {
		return m.SongID
	}
	return ""
}

type DeleteSongRequest struct {
	SongID               string   `protobuf:"bytes,1,opt,name=SongID,proto3" json:"SongID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSongRequest) Reset()         { *m = DeleteSongRequest{} }
func (m *DeleteSongRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSongRequest) ProtoMessage()    {}
func (*DeleteSongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a965d53506cc0f82, []int{4}
}

func (m *DeleteSongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSongRequest.Unmarshal(m, b)
}
func (m *DeleteSongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSongRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSongRequest.Merge(m, src)
}
func (m *DeleteSongRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSongRequest.Size(m)
}
func (m *DeleteSongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSongRequest proto.InternalMessageInfo

func (m *DeleteSongRequest) GetSongID() string {
	if m != nil {
		return m.SongID
	}
	return ""
}

type Song struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artists              []string `protobuf:"bytes,2,rep,name=artists,proto3" json:"artists,omitempty"`
	Audio                []byte   `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Song) Reset()         { *m = Song{} }
func (m *Song) String() string { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()    {}
func (*Song) Descriptor() ([]byte, []int) {
	return fileDescriptor_a965d53506cc0f82, []int{5}
}

func (m *Song) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Song.Unmarshal(m, b)
}
func (m *Song) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Song.Marshal(b, m, deterministic)
}
func (m *Song) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Song.Merge(m, src)
}
func (m *Song) XXX_Size() int {
	return xxx_messageInfo_Song.Size(m)
}
func (m *Song) XXX_DiscardUnknown() {
	xxx_messageInfo_Song.DiscardUnknown(m)
}

var xxx_messageInfo_Song proto.InternalMessageInfo

func (m *Song) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Song) GetArtists() []string {
	if m != nil {
		return m.Artists
	}
	return nil
}

func (m *Song) GetAudio() []byte {
	if m != nil {
		return m.Audio
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a965d53506cc0f82, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddSongRequest)(nil), "songservice.AddSongRequest")
	proto.RegisterType((*UpdateSongRequest)(nil), "songservice.UpdateSongRequest")
	proto.RegisterType((*GetSongRequest)(nil), "songservice.GetSongRequest")
	proto.RegisterType((*GetSongResponse)(nil), "songservice.GetSongResponse")
	proto.RegisterType((*GetSongResponse_GetSongResult)(nil), "songservice.GetSongResponse.GetSongResult")
	proto.RegisterType((*DeleteSongRequest)(nil), "songservice.DeleteSongRequest")
	proto.RegisterType((*Song)(nil), "songservice.Song")
	proto.RegisterType((*Empty)(nil), "songservice.Empty")
}

func init() { proto.RegisterFile("api/songservice.proto", fileDescriptor_a965d53506cc0f82) }

var fileDescriptor_a965d53506cc0f82 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0x92, 0xb4, 0x29, 0x9d, 0x7c, 0x56, 0x3a, 0xa8, 0x84, 0x2a, 0x52, 0x16, 0x84, 0x62,
	0xa1, 0x42, 0x7b, 0xf1, 0xa2, 0xd0, 0x52, 0x29, 0x7a, 0xf0, 0x90, 0xa2, 0x67, 0xa3, 0x19, 0x4a,
	0xa0, 0x4d, 0x62, 0x76, 0xa3, 0xf8, 0x1b, 0xfc, 0x1d, 0xfe, 0x4f, 0xc9, 0x6e, 0x2b, 0xbb, 0xad,
	0x2d, 0x78, 0xdb, 0xb7, 0xf3, 0xe6, 0xcd, 0xcb, 0xcb, 0x2c, 0x1c, 0x86, 0x59, 0x7c, 0xc1, 0xd3,
	0x64, 0xc6, 0x29, 0x7f, 0x8b, 0x5f, 0xa8, 0x97, 0xe5, 0xa9, 0x48, 0xd1, 0xd3, 0xae, 0xd8, 0x15,
	0x34, 0x86, 0x51, 0x34, 0x4d, 0x93, 0x59, 0x40, 0xaf, 0x05, 0x71, 0x81, 0x5d, 0xa8, 0x25, 0xf4,
	0x5e, 0xde, 0xf8, 0x56, 0xdb, 0xea, 0x78, 0xfd, 0x66, 0x4f, 0xd7, 0x90, 0xd4, 0x15, 0x83, 0x3d,
	0x41, 0xf3, 0x21, 0x8b, 0x42, 0x41, 0xba, 0xc2, 0x11, 0xb8, 0x65, 0xc7, 0xed, 0x58, 0x0a, 0xd4,
	0x83, 0x25, 0xc2, 0x01, 0x78, 0x85, 0x24, 0xcb, 0x79, 0xbe, 0xbd, 0x4d, 0x5d, 0x67, 0xb1, 0x47,
	0x68, 0x4c, 0x48, 0xe8, 0xf2, 0x08, 0x95, 0x24, 0x5c, 0xd0, 0x52, 0x5c, 0x9e, 0xd1, 0x87, 0x5a,
	0x98, 0x8b, 0x98, 0x0b, 0xee, 0xdb, 0x6d, 0xa7, 0x53, 0x0f, 0x56, 0x50, 0x33, 0xe3, 0xe8, 0x66,
	0xd8, 0x97, 0x05, 0xfb, 0x3f, 0xc2, 0x3c, 0x4b, 0x13, 0x4e, 0x38, 0x02, 0x37, 0x27, 0x5e, 0xcc,
	0x85, 0x6f, 0xb5, 0x9d, 0x8e, 0xd7, 0x3f, 0x37, 0xbc, 0xad, 0xb1, 0x35, 0x5c, 0xcc, 0x45, 0xb0,
	0xec, 0x6c, 0xdd, 0xc3, 0x9e, 0x51, 0xc0, 0x33, 0xa8, 0xf0, 0x9d, 0x61, 0xca, 0xb2, 0xe6, 0xd3,
	0x36, 0x7c, 0x76, 0xa1, 0x39, 0xa6, 0x39, 0x6d, 0x24, 0x3c, 0x35, 0x12, 0x56, 0x88, 0xdd, 0x41,
	0xa5, 0x3c, 0xfd, 0x31, 0xa2, 0x03, 0xa8, 0x86, 0x45, 0x14, 0xa7, 0x32, 0xa1, 0xff, 0x81, 0x02,
	0xac, 0x06, 0xd5, 0x9b, 0x45, 0x26, 0x3e, 0xfa, 0x9f, 0x36, 0x78, 0xa5, 0xea, 0x54, 0x99, 0xc6,
	0x4b, 0x70, 0x86, 0x51, 0x84, 0xc7, 0xc6, 0x97, 0x98, 0x4b, 0xd4, 0x42, 0xa3, 0x28, 0x75, 0xd8,
	0x3f, 0xbc, 0x06, 0x57, 0x6d, 0x0b, 0x9e, 0x1a, 0xf5, 0x8d, 0x15, 0xda, 0xd2, 0x3f, 0x02, 0x67,
	0x42, 0x62, 0x6d, 0xb2, 0xb9, 0x1d, 0xad, 0x93, 0x5d, 0xff, 0x4c, 0x79, 0x50, 0x79, 0xae, 0x79,
	0xd8, 0x08, 0xf9, 0x77, 0x0f, 0xcf, 0xae, 0x7c, 0x44, 0x83, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3c, 0x86, 0xba, 0xdb, 0x5d, 0x03, 0x00, 0x00,
}
